/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank.atm.management;

import bank.atm.management.image.Bank;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author Administrator
 */
public class Login extends javax.swing.JFrame {

    String driver = "com.mysql.jdbc.Driver";
    String url = "jdbc:mysql://localhost:3306/inventory";
    Connection con;
    Statement stm;
    PreparedStatement pprds;
    String sqls;
    ResultSet rs;
    String AccountNo;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    public void myDriver() {
        try {
            Class.forName(driver);
            con = DriverManager.getConnection(url, "root", "admin");
        } catch (ClassNotFoundException cnf) {
            System.out.println(cnf);
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, sqle);
        }
    }
    SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
    String Date = sdf.format(new Date());
    SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss");
    Date date = new Date();
    String newDate = df.format(date);
    String time = (date.getHours()) + ":" + (date.getMinutes()) + ":" + (date.getSeconds());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        upass = new javax.swing.JPasswordField();
        uid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        showPass = new javax.swing.JCheckBox();
        SignupPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        SignupPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        SignupPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ExitPanel1 = new javax.swing.JPanel();
        forgettext1 = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        forgettext = new javax.swing.JLabel();
        SignupPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Noakhali Bank");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/atm/management/image/bank sign2.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("We provide Digital Banking Facility");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Password");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/atm/management/image/icons8-password-30.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("User Name");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/atm/management/image/menIcon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(87, 87, 87))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
        );

        upass.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        upass.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        uid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        uid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setBackground(new java.awt.Color(30, 132, 73));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/atm/management/image/undraw_profile_pic_ic5t.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Welcome");

        showPass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        showPass.setText("Show Password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upass, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showPass))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(showPass)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        SignupPanel2.setBackground(new java.awt.Color(0, 20, 252));

        SignupPanel3.setBackground(new java.awt.Color(0, 0, 255));
        SignupPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignupPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignupPanel3PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignupPanel3PanelMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Noakhali Bank");

        jLabel22.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Noakhali's Number One Online Bank");

        javax.swing.GroupLayout SignupPanel3Layout = new javax.swing.GroupLayout(SignupPanel3);
        SignupPanel3.setLayout(SignupPanel3Layout);
        SignupPanel3Layout.setHorizontalGroup(
            SignupPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(SignupPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SignupPanel3Layout.setVerticalGroup(
            SignupPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        SignupPanel.setBackground(new java.awt.Color(0, 0, 255));
        SignupPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignupPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignupPanelPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignupPanelPanelMouseExited(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Create Account");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SignupPanelLayout = new javax.swing.GroupLayout(SignupPanel);
        SignupPanel.setLayout(SignupPanelLayout);
        SignupPanelLayout.setHorizontalGroup(
            SignupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SignupPanelLayout.setVerticalGroup(
            SignupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/atm/management/image/pngwing.com.png"))); // NOI18N

        ExitPanel1.setBackground(new java.awt.Color(0, 0, 255));
        ExitPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitPanel1.setPreferredSize(new java.awt.Dimension(128, 48));
        ExitPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitPanel1PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitPanel1PanelMouseExited(evt);
            }
        });

        forgettext1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        forgettext1.setForeground(new java.awt.Color(255, 255, 255));
        forgettext1.setText("Exit");

        javax.swing.GroupLayout ExitPanel1Layout = new javax.swing.GroupLayout(ExitPanel1);
        ExitPanel1.setLayout(ExitPanel1Layout);
        ExitPanel1Layout.setHorizontalGroup(
            ExitPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(forgettext1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExitPanel1Layout.setVerticalGroup(
            ExitPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forgettext1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ExitPanel.setBackground(new java.awt.Color(0, 0, 255));
        ExitPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitPanelPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitPanelPanelMouseExited(evt);
            }
        });

        forgettext.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        forgettext.setForeground(new java.awt.Color(255, 255, 255));
        forgettext.setText("Home");

        javax.swing.GroupLayout ExitPanelLayout = new javax.swing.GroupLayout(ExitPanel);
        ExitPanel.setLayout(ExitPanelLayout);
        ExitPanelLayout.setHorizontalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(forgettext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExitPanelLayout.setVerticalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forgettext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SignupPanel1.setBackground(new java.awt.Color(0, 0, 255));
        SignupPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignupPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignupPanel1PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignupPanel1PanelMouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("System");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SignupPanel1Layout = new javax.swing.GroupLayout(SignupPanel1);
        SignupPanel1.setLayout(SignupPanel1Layout);
        SignupPanel1Layout.setHorizontalGroup(
            SignupPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SignupPanel1Layout.setVerticalGroup(
            SignupPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SignupPanel2Layout = new javax.swing.GroupLayout(SignupPanel2);
        SignupPanel2.setLayout(SignupPanel2Layout);
        SignupPanel2Layout.setHorizontalGroup(
            SignupPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SignupPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SignupPanel2Layout.createSequentialGroup()
                .addGroup(SignupPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignupPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(SignupPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SignupPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ExitPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                    .addComponent(ExitPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SignupPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SignupPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SignupPanel2Layout.setVerticalGroup(
            SignupPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel21)
                .addGap(37, 37, 37)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignupPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(ExitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignupPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExitPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SignupPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        myDriver();

        try {
            if (uid.getText().equals("") || upass.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please fill the Username & Password Field", "Login Error!", JOptionPane.ERROR_MESSAGE);
                uid.requestFocus();
            } else {
                int user = Integer.parseInt(uid.getText());
                stm = con.createStatement();
                //select aes_decrypt(trainor_password, 'key') from trainor where trainor_id=1002;
                rs = stm.executeQuery("select id, first_name, last_name, password, date from employees where id=" + Integer.parseInt(uid.getText()) + "&& password='" + upass.getText() + "'");
                if (rs.next()) {
                    //System.out.println(rs);
                    //s = rs.getString("user_pass");
                    String n = rs.getString("First_Name") + " " + rs.getString("Last_Name");
                    String cdate = rs.getString("date");
                    String query = "insert into userinfo values(" + Integer.parseInt(uid.getText()) + ",'" + n + "','" + cdate + "','" + Date + " " + time + "','" + "N/A')";
                    PreparedStatement pst5 = con.prepareStatement(query);
                    pst5.execute();
                    this.setVisible(false);
                    dispose();
                    new MyDashboard(user).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(Login.this, "Sorry, Username or Password is Wrong", "Login Error!", JOptionPane.ERROR_MESSAGE);
                    uid.requestFocus();
                }
            }
        } catch (SQLException sqle) {
            System.out.println(sqle);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SignupPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupPanel3MouseClicked
//        // TODO add your handling code here:
//        CreateAccount AC = new CreateAccount();
//        setVisible(false);
//        dispose();
//        AC.setVisible(true);
    }//GEN-LAST:event_SignupPanel3MouseClicked

    private void SignupPanel3PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupPanel3PanelMouseEntered
        // TODO add your handling code here:
        if (evt.getSource() == SignupPanel2) {                           // This event is as similar as above event
            SignupPanel2.setBackground(new Color(9, 50, 236));
        }
        if (evt.getSource() == SignupPanel) {
            SignupPanel.setBackground(new Color(9, 50, 236));
        }
        if (evt.getSource() == ExitPanel) {
            ExitPanel.setBackground(new Color(9, 50, 236));
        }
    }//GEN-LAST:event_SignupPanel3PanelMouseEntered

    private void SignupPanel3PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupPanel3PanelMouseExited
        if (evt.getSource() == SignupPanel2) {                           // if mouse exited from signup panel it change color
            // evt.getSource check the particular mouse pointer leav or enter
            // accourding to that it react
            SignupPanel2.setBackground(new Color(0, 0, 225));
        }
        if (evt.getSource() == SignupPanel) {
            SignupPanel.setBackground(new Color(0, 0, 225));
        }
        if (evt.getSource() == ExitPanel) {
            ExitPanel.setBackground(new Color(0, 0, 225));
        }
    }//GEN-LAST:event_SignupPanel3PanelMouseExited

    private void SignupPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupPanelMouseClicked
//        setVisible(false);
//        dispose();
//        new ResetPassword().setVisible(true);
    }//GEN-LAST:event_SignupPanelMouseClicked

    private void SignupPanelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupPanelPanelMouseEntered
        // TODO add your handling code here:
        if (evt.getSource() == SignupPanel2) {                           // This event is as similar as above event
            SignupPanel2.setBackground(new Color(9, 50, 236));
        }
        if (evt.getSource() == SignupPanel) {
            SignupPanel.setBackground(new Color(9, 50, 236));
        }
        if (evt.getSource() == ExitPanel) {
            ExitPanel.setBackground(new Color(9, 50, 236));
        }
    }//GEN-LAST:event_SignupPanelPanelMouseEntered

    private void SignupPanelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupPanelPanelMouseExited
        if (evt.getSource() == SignupPanel2) {                           // if mouse exited from signup panel it change color
            // evt.getSource check the particular mouse pointer leav or enter
            // accourding to that it react
            SignupPanel2.setBackground(new Color(0, 0, 225));
        }
        if (evt.getSource() == SignupPanel) {
            SignupPanel.setBackground(new Color(0, 0, 225));
        }
        if (evt.getSource() == ExitPanel) {
            ExitPanel.setBackground(new Color(0, 0, 225));
        }
    }//GEN-LAST:event_SignupPanelPanelMouseExited

    private void ExitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseClicked
        this.setVisible(false);
        dispose();
        new Home1().setVisible(true);
    }//GEN-LAST:event_ExitPanelMouseClicked

    private void ExitPanelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelPanelMouseEntered
        // TODO add your handling code here:
        if (evt.getSource() == SignupPanel2) {                           // This event is as similar as above event
            SignupPanel2.setBackground(new Color(9, 50, 236));
        }
        if (evt.getSource() == SignupPanel) {
            SignupPanel.setBackground(new Color(9, 50, 236));
        }
        if (evt.getSource() == ExitPanel) {
            ExitPanel.setBackground(new Color(9, 50, 236));
        }
    }//GEN-LAST:event_ExitPanelPanelMouseEntered

    private void ExitPanelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelPanelMouseExited
        if (evt.getSource() == SignupPanel2) {                           // if mouse exited from signup panel it change color
            // evt.getSource check the particular mouse pointer leav or enter
            // accourding to that it react
            SignupPanel2.setBackground(new Color(0, 0, 225));
        }
        if (evt.getSource() == SignupPanel) {
            SignupPanel.setBackground(new Color(0, 0, 225));
        }
        if (evt.getSource() == ExitPanel) {
            ExitPanel.setBackground(new Color(0, 0, 225));
        }
    }//GEN-LAST:event_ExitPanelPanelMouseExited

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        this.setVisible(false);
        dispose();
        new createAccount().setVisible(true);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void ExitPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitPanel1MouseClicked

    private void ExitPanel1PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanel1PanelMouseEntered
        if (evt.getSource() == forgettext1) {                           // This event is as similar as above event
            forgettext1.setBackground(new Color(231, 76, 60));
        }
        if (evt.getSource() == ExitPanel1) {
            ExitPanel1.setBackground(new Color(231, 76, 60));
        }
        if (evt.getSource() == ExitPanel) {
            ExitPanel.setBackground(new Color(231, 76, 60));
        }
    }//GEN-LAST:event_ExitPanel1PanelMouseEntered

    private void ExitPanel1PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanel1PanelMouseExited
        if (evt.getSource() == forgettext1) {                           // if mouse exited from signup panel it change color
            // evt.getSource check the particular mouse pointer leav or enter
            // accourding to that it react
            forgettext1.setBackground(new Color(0, 0, 225));
        }
        if (evt.getSource() == ExitPanel1) {
            ExitPanel1.setBackground(new Color(0, 0, 225));
        }
        if (evt.getSource() == ExitPanel) {
            ExitPanel.setBackground(new Color(0, 0, 225));
        }
    }//GEN-LAST:event_ExitPanel1PanelMouseExited

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed

        if (showPass.isSelected()) {
            upass.setEchoChar((char) 0);
        } else {
            upass.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void SignupPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupPanel1MouseClicked
        Box box = Box.createHorizontalBox();

        JLabel jl = new JLabel("Password: ");
        box.add(jl);

        JPasswordField jpf = new JPasswordField(16);
        box.add(jpf);

        int button = JOptionPane.showConfirmDialog(null, box, "Enter your password", JOptionPane.OK_CANCEL_OPTION);
        String pass = "admin";

        if (button == JOptionPane.OK_OPTION) {
            char[] input = jpf.getPassword();
            String enteredPass = String.valueOf(input);
            if (enteredPass.equals("")) {
                JOptionPane.showMessageDialog(this, "Please fill the Password Field", "Login Error!", JOptionPane.ERROR_MESSAGE);
            } else if (enteredPass.equals(pass)) {
                myDriver();
                int id;
                try {
                    String n="admin";
                    String cdate="2022-05-01";
                     id=1000;
                    String query = "insert into userinfo values(" + id + ",'" + n + "','" + cdate + "','" + Date + " " + time + "','" + "N/A')";
                    PreparedStatement pst5 = con.prepareStatement(query);
                    pst5.execute();
                    this.setVisible(false);
                    dispose();
                    new Report(id).setVisible(true);
                } catch (SQLException e) {
                    e.printStackTrace();
                }

            } else {
                JOptionPane.showMessageDialog(this, "Wrong Password !\nThis page only for Admin\nPlease contact him", "Login Error!", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_SignupPanel1MouseClicked

    private void SignupPanel1PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupPanel1PanelMouseEntered
        if (evt.getSource() == SignupPanel1) {                           // This event is as similar as above event
            SignupPanel1.setBackground(new Color(9, 50, 236));
        }
        if (evt.getSource() == SignupPanel) {
            SignupPanel.setBackground(new Color(9, 50, 236));
        }
        if (evt.getSource() == ExitPanel) {
            ExitPanel.setBackground(new Color(9, 50, 236));
        }
    }//GEN-LAST:event_SignupPanel1PanelMouseEntered

    private void SignupPanel1PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupPanel1PanelMouseExited
        if (evt.getSource() == SignupPanel1) {                           // if mouse exited from signup panel it change color
            // evt.getSource check the particular mouse pointer leav or enter
            // accourding to that it react
            SignupPanel1.setBackground(new Color(0, 0, 225));
        }
        if (evt.getSource() == SignupPanel) {
            SignupPanel.setBackground(new Color(0, 0, 225));
        }
        if (evt.getSource() == ExitPanel) {
            ExitPanel.setBackground(new Color(0, 0, 225));
        }
    }//GEN-LAST:event_SignupPanel1PanelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JPanel ExitPanel1;
    private javax.swing.JPanel SignupPanel;
    private javax.swing.JPanel SignupPanel1;
    private javax.swing.JPanel SignupPanel2;
    private javax.swing.JPanel SignupPanel3;
    private javax.swing.JLabel forgettext;
    private javax.swing.JLabel forgettext1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JTextField uid;
    private javax.swing.JPasswordField upass;
    // End of variables declaration//GEN-END:variables
}
